export const dataList = [
  {
    id: 1,
    name: "Residential Plots",
    location: "Sy No 61, Khata No 354/61, Gottigere, South Bangalore,Bangalore",
    home: "Villa",
    square: "2, 3 BHK Appartment",
    area: 1800,
    price: 5000,
    move: "Ready to move",
  },
  {
    id: 2,
    name: "Appartment",
    location: "Sy No 61, Khata No 354/61, Gottigere, South Bangalore,Bangalore",
    home: "Villa",
    square: "2, 3 BHK Appartment",
    area: 2000,
    price: 3000,
    move: "New Launch",
  },
  {
    id: 3,
    name: "CasaGrand Hazen",
    location: "Sy No 61, Khata No 354/61, Gottigere, South Bangalore,Bangalore",
    home: "Villa",
    square: "+ 1 RK/1 BHK",
    area: 690,
    price: 2500,
    move: "Under Construction",
  },
  {
    id: 4,
    name: "Studio",
    location: "Sy No 61, Khata No 354/61, Gottigere, South Bangalore,Bangalore",
    home: "Villa",
    square: "+ 4 BHK",
    area: 5600,
    price: 520,
    move: "New Launch",
  },
  {
    id: 5,
    name: "Duplex",
    location: "Sy No 61, Khata No 354/61, Gottigere, South Bangalore,Bangalore",
    home: "Villa",
    square: "+ 3 BHK",
    area: 3500,
    price: 1500,
    move: "Under Construction",
  },
  {
    id: 6,
    name: "Villa",
    location: "Sy No 61, Khata No 354/61, Gottigere, South Bangalore,Bangalore",
    home: "Villa",
    square: "+ 2 BHK",
    area: 2600,
    price: 4000,
    move: "Ready to move",
  },
  {
    id: 7,
    name: "Agricultural Land",
    location: "Sy No 61, Khata No 354/61, Gottigere, South Bangalore,Bangalore",
    home: "Villa",
    square: "+ 1 RK/1 BHK",
    area: 3100,
    price: 3500,
    move: "Ready to move",
  },
];

export const buttonList = [
  {
    id: 1,
    value: "+ 1 RK/1 BHK",
    label: "+ 1 RK/1 BHK",
  },
  {
    id: 2,
    value: "+ 2 BHK",
    label: "+ 2 BHK",
  },
  {
    id: 3,
    value: "+ 3 BHK",
    label: "+ 3 BHK",
  },
  {
    id: 4,
    value: "+ 4 BHK",
    label: "+ 4 BHK",
  },
  {
    id: 5,
    value: "+ 5 BHK",
    label: "+ 5 BHK",
  },
];
