const dataList = [
  {
    id: 1,
    name: "Residential Plots",
    location: "Sy No 61, Khata No 354/61, Gottigere, South Bangalore,Bangalore",
    home: "Villa",
    square: "2, 3 BHK Appartment",
    area: "2000-5000 sq.ft.",
    price: 30000,
  },
  {
    id: 2,
    name: "Appartment",
    location: "Sy No 61, Khata No 354/61, Gottigere, South Bangalore,Bangalore",
    home: "Villa",
    square: "2, 3 BHK Appartment",
    area: "2000-5000 sq.ft.",
    price: 3000,
  },
  {
    id: 3,
    name: "CasaGrand Hazen",
    location: "Sy No 61, Khata No 354/61, Gottigere, South Bangalore,Bangalore",
    home: "Villa",
    square: "+ 1 RK/1 BHK",
    area: "2000-5000 sq.ft.",
    price: 25000,
  },
  {
    id: 4,
    name: "Studio",
    location: "Sy No 61, Khata No 354/61, Gottigere, South Bangalore,Bangalore",
    home: "Villa",
    square: "+ 4 BHK",
    area: "2000-5000 sq.ft.",
    price: 25000,
  },
  {
    id: 5,
    name: "Duplex",
    location: "Sy No 61, Khata No 354/61, Gottigere, South Bangalore,Bangalore",
    home: "Villa",
    square: "+ 3 BHK",
    area: "2000-5000 sq.ft.",
    price: 25000,
  },
  {
    id: 6,
    name: "Villa",
    location: "Sy No 61, Khata No 354/61, Gottigere, South Bangalore,Bangalore",
    home: "Villa",
    square: "+ 2 BHK",
    area: "2000-5000 sq.ft.",
    price: 25000,
  },
  {
    id: 7,
    name: "Agricultural Land",
    location: "Sy No 61, Khata No 354/61, Gottigere, South Bangalore,Bangalore",
    home: "Villa",
    square: "+ 1 RK/1 BHK",
    area: "2000-5000 sq.ft.",
    price: 25000,
  },
];

export default dataList;
